### ISSUE TITLE
How to download coco

### ISSUE THREAD

**Issue by dev-ptdi** [nicolasmetallo/car-damage-detector#6]
python3 custom.py --dataset='output' --weights=coco

but it does not download coco, it returns below, I am not using GPU
please help me to move forward

many thanks

2020-06-22 11:10:17.254678: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-06-22 11:10:17.255093: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using TensorFlow backend.
usage: custom.py [-h] [--dataset /path/to/custom/dataset/] --weights /path/to/weights.h5 [--logs /path/to/logs/] [--image path or URL to image] [--video path or URL to video] <command>
custom.py: error: the following arguments are required: <command>

**Comment by Muhammad-Talha-MT** [comment]
I had same problem
`usage: custom.py [-h] [--dataset /path/to/custom/dataset/] --weights /path/to/weights.h5 [--logs /path/to/logs/]
                 [--image path or URL to image] [--video path or URL to video]
                 <command>
custom.py: error: the following arguments are required: <command>
`
Then I tried this command
`python3 custom.py train --dataset='dataset' --weights=coco
`
Now I am facing another error
`2020-10-13 11:12:25.202133: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-10-13 11:12:25.202171: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-10-13 11:12:25.202207: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (talha-TravelMate-P246-M): /proc/driver/nvidia/version does not exist
2020-10-13 11:12:25.202435: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-10-13 11:12:25.228419: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2394445000 Hz
2020-10-13 11:12:25.228811: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f01dc000b60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-13 11:12:25.228851: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "custom.py", line 326, in <module>
    model = modellib.MaskRCNN(mode="training", config=config,
  File "/home/talha/RCNN/car-damage-detector/mrcnn/model.py", line 1837, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/home/talha/RCNN/car-damage-detector/mrcnn/model.py", line 1934, in build
    anchors = KL.Lambda(lambda x: tf.Variable(anchors), name="anchors")(input_image)
  File "/home/talha/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 922, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/talha/.local/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py", line 889, in call
    self._check_variables(created_variables, tape.watched_variables())
  File "/home/talha/.local/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py", line 916, in _check_variables
    raise ValueError(error_str)
ValueError: 
The following Variables were created within a Lambda layer (anchors)
but are not tracked by said layer:
  <tf.Variable 'anchors/Variable:0' shape=(2, 261888, 4) dtype=float32>
The layer cannot safely ensure proper Variable reuse across multiple
calls, and consquently this behavior is disallowed for safety. Lambda
layers are not well suited to stateful computation; instead, writing a
subclassed Layer is the recommend way to define layers with
Variables.`
